### ISSUE TITLE
Request: Reverse process to make profiles.xml readable.

### ISSUE THREAD

**Issue by rhogg4999** [Loo0D/atn-xml-convert#1]
Thank you for creating this very useful utility for creating profiles.xml files. What is missing is translating the profiles.xml back to .toml or something more readable. 

I make changes to the ATN when at the range or in the field, for example, chrono results or re-zeroing. Unless I write them down at the time it is a pain to transcribe them from the ATN unit etc.

I see that you already have the encode/decode coding already written. What is needed is maybe a "-i <input.xml>" alternative to -f etc.

**Comment by Loo0D** [comment]
Good point well made! I'll add it.

**Comment by Loo0D** [comment]
v0.3 now out
